name: benchmarks

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  runbenchmarks:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'

      - name: run benchmarks
        run: julia --project=benchmark/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); include("benchmark/runbenchmarks.jl")'

      - uses: actions/upload-artifact@v4
        with:
          name: monty-benchmarks
          path: benchmarks.json
