name: tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.10']
        julia-arch: [x64, x86]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        exclude:
          - os: macOS-latest
            julia-arch: x86
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
